import 'dart:io';

class VINDecoder {
  static const Map<String, String> countryCodes = {
    'AA': 'South Africa',
    'AB': 'South Africa',
    'AC': 'South Africa',
    'AD': 'South Africa',
    'AE': 'South Africa',
    'AF': 'South Africa',
    'AG': 'South Africa',
    'AH': 'South Africa',
    'AJ': 'Côte d\'Ivoire',
    'AK': 'Côte d\'Ivoire',
    'AL': 'Côte d\'Ivoire',
    'AM': 'Côte d\'Ivoire',
    'AN': 'Côte d\'Ivoire',
    'BA': 'Angola',
    'BB': 'Angola',
    'BC': 'Angola',
    'BD': 'Angola',
    'BE': 'Angola',
    'BF': 'Kenya',
    'BG': 'Kenya',
    'BH': 'Kenya',
    'BI': 'Kenya',
    'BJ': 'Kenya',
    'BK': 'Kenya',
    'BL': 'Tanzania',
    'BM': 'Tanzania',
    'BN': 'Tanzania',
    'BO': 'Tanzania',
    'BP': 'Tanzania',
    'BQ': 'Tanzania',
    'BR': 'Tanzania',
    'BU': 'Uganda',
    'CA': 'Benin',
    'CB': 'Benin',
    'CC': 'Benin',
    'CD': 'Benin',
    'CE': 'Benin',
    'CF': 'Madagascar',
    'CG': 'Madagascar',
    'CH': 'Madagascar',
    'CI': 'Madagascar',
    'CJ': 'Madagascar',
    'CK': 'Madagascar',
    'CL': 'Tunisia',
    'CM': 'Tunisia',
    'CN': 'Tunisia',
    'CO': 'Tunisia',
    'CP': 'Tunisia',
    'CQ': 'Tunisia',
    'CR': 'Tunisia',
    'DA': 'Egypt',
    'DB': 'Egypt',
    'DC': 'Egypt',
    'DD': 'Egypt',
    'DE': 'Egypt',
    'DF': 'Morocco',
    'DG': 'Morocco',
    'DH': 'Morocco',
    'DI': 'Morocco',
    'DJ': 'Morocco',
    'DK': 'Morocco',
    'DL': 'Zambia',
    'DM': 'Zambia',
    'DN': 'Zambia',
    'DO': 'Zambia',
    'DP': 'Zambia',
    'DQ': 'Zambia',
    'DR': 'Zambia',
    'EA': 'Ethiopia',
    'EB': 'Ethiopia',
    'EC': 'Ethiopia',
    'ED': 'Ethiopia',
    'EE': 'Ethiopia',
    'EF': 'Mozambique',
    'EG': 'Mozambique',
    'EH': 'Mozambique',
    'EI': 'Mozambique',
    'EJ': 'Mozambique',
    'EK': 'Mozambique',
    'FA': 'Ghana',
    'FB': 'Ghana',
    'FC': 'Ghana',
    'FD': 'Ghana',
    'FE': 'Ghana',
    'FF': 'Nigeria',
    'FG': 'Nigeria',
    'FH': 'Nigeria',
    'FI': 'Nigeria',
    'FJ': 'Nigeria',
    'FK': 'Nigeria',
    'J': 'Japan',
    'KA': 'Sri Lanka',
    'KB': 'Sri Lanka',
    'KC': 'Sri Lanka',
    'KD': 'Sri Lanka',
    'KE': 'Sri Lanka',
    'KF': 'Israel',
    'KG': 'Israel',
    'KH': 'Israel',
    'KI': 'Israel',
    'KJ': 'Israel',
    'KK': 'Israel',
    'KL': 'Korea (South)',
    'KM': 'Korea (South)',
    'KN': 'Korea (South)',
    'KO': 'Korea (South)',
    'KP': 'Korea (South)',
    'KQ': 'Korea (South)',
    'KR': 'Korea (South)',
    'KS': 'Jordan',
    'KT': 'Jordan',
    'L': 'China (Mainland)',
    'MA': 'India',
    'MB': 'India',
    'MC': 'India',
    'MD': 'India',
    'ME': 'India',
    'MY': 'India',
    'MZ': 'India',
    'MF': 'Indonesia',
    'MG': 'Indonesia',
    'MH': 'Indonesia',
    'MI': 'Indonesia',
    'MJ': 'Indonesia',
    'MK': 'Indonesia',
    'ML': 'Thailand',
    'MM': 'Thailand',
    'MN': 'Thailand',
    'MO': 'Thailand',
    'MP': 'Thailand',
    'MQ': 'Thailand',
    'MR': 'Thailand',
    'MS': 'Myanmar',
    'MT': 'Myanmar',
    'MU': 'Mongolia',
    'MV': 'Mongolia',
    'MW': 'Mongolia',
    'MX': 'Kazakhstan',
    'NA': 'Iran',
    'NB': 'Iran',
    'NC': 'Iran',
    'ND': 'Iran',
    'NE': 'Iran',
    'NF': 'Pakistan',
    'NG': 'Pakistan',
    'NH': 'Pakistan',
    'NI': 'Pakistan',
    'NJ': 'Pakistan',
    'NK': 'Pakistan',
    'NL': 'Turkey',
    'NM': 'Turkey',
    'NN': 'Turkey',
    'NO': 'Turkey',
    'NP': 'Turkey',
    'NQ': 'Turkey',
    'NR': 'Turkey',
    'NS': 'Uzbekistan',
    'NT': 'Uzbekistan',
    'PA': 'Philippines',
    'PB': 'Philippines',
    'PC': 'Philippines',
    'PD': 'Philippines',
    'PE': 'Philippines',
    'PF': 'Singapore',
    'PG': 'Singapore',
    'PH': 'Singapore',
    'PI': 'Singapore',
    'PJ': 'Singapore',
    'PK': 'Singapore',
    'PL': 'Malaysia',
    'PM': 'Malaysia',
    'PN': 'Malaysia',
    'PO': 'Malaysia',
    'PP': 'Malaysia',
    'PQ': 'Malaysia',
    'PR': 'Malaysia',
    'PS': 'Bangladesh',
    'PT': 'Bangladesh',
    'RA': 'United Arab Emirates',
    'RB': 'United Arab Emirates',
    'RC': 'United Arab Emirates',
    'RD': 'United Arab Emirates',
    'RE': 'United Arab Emirates',
    'RF': 'Taiwan',
    'RG': 'Taiwan',
    'RH': 'Taiwan',
    'RI': 'Taiwan',
    'RJ': 'Taiwan',
    'RK': 'Taiwan',
    'RL': 'Vietnam',
    'RM': 'Vietnam',
    'RN': 'Vietnam',
    'RO': 'Vietnam',
    'RP': 'Vietnam',
    'RS': 'Saudi Arabia',
    'RT': 'Saudi Arabia',
    'R1': 'Hongkong',
    'R2': 'Hongkong',
    'R3': 'Hongkong',
    'R4': 'Hongkong',
    'R5': 'Hongkong',
    'R6': 'Hongkong',
    'R7': 'Hongkong',
    'SA': 'United Kingdom',
    'SB': 'United Kingdom',
    'SC': 'United Kingdom',
    'SD': 'United Kingdom',
    'SE': 'United Kingdom',
    'SF': 'United Kingdom',
    'SG': 'United Kingdom',
    'SH': 'United Kingdom',
    'SI': 'United Kingdom',
    'SJ': 'United Kingdom',
    'SK': 'United Kingdom',
    'SL': 'United Kingdom',
    'SM': 'United Kingdom',
    'SN': 'Germany',
    'SO': 'Germany',
    'SP': 'Germany',
    'SQ': 'Germany',
    'SR': 'Germany',
    'SS': 'Germany',
    'ST': 'Germany',
    'SU': 'Poland',
    'SV': 'Poland',
    'SW': 'Poland',
    'SX': 'Poland',
    'SY': 'Poland',
    'SZ': 'Poland',
    'S1': 'Latvia',
    'S2': 'Latvia',
    'S3': 'Georgia',
    'S4': 'Iceland',
    'TA': 'Switzerland',
    'TB': 'Switzerland',
    'TC': 'Switzerland',
    'TD': 'Switzerland',
    'TE': 'Switzerland',
    'TF': 'Switzerland',
    'TG': 'Switzerland',
    'TH': 'Switzerland',
    'TJ': 'Czech Republic',
    'TK': 'Czech Republic',
    'TL': 'Czech Republic',
    'TM': 'Czech Republic',
    'TN': 'Czech Republic',
    'TO': 'Czech Republic',
    'TP': 'Czech Republic',
    'TR': 'Hungary',
    'TS': 'Hungary',
    'TT': 'Hungary',
    'TU': 'Hungary',
    'TV': 'Hungary',
    'TW': 'Portugal',
    'TX': 'Portugal',
    'TY': 'Portugal',
    'TZ': 'Portugal',
    'T1': 'Portugal',
    'T2': 'Portugal',
    'UA': 'Unassigned',
    'UB': 'Unassigned',
    'UC': 'Unassigned',
    'UD': 'Unassigned',
    'UE': 'Unassigned',
    'UF': 'Unassigned',
    'UG': 'Unassigned',
    'UH': 'Denmark',
    'UI': 'Denmark',
    'UJ': 'Denmark',
    'UK': 'Denmark',
    'UL': 'Denmark',
    'UM': 'Denmark',
    'UN': 'Ireland',
    'UO': 'Ireland',
    'UP': 'Ireland',
    'UQ': 'Ireland',
    'UR': 'Ireland',
    'US': 'Ireland',
    'UT': 'Ireland',
    'UU': 'Romania',
    'UV': 'Romania',
    'UW': 'Romania',
    'UX': 'Romania',
    'UY': 'Romania',
    'UZ': 'Romania',
    'U1': 'North Macedonia',
    'U2': 'North Macedonia',
    'U3': 'North Macedonia',
    'U4': 'North Macedonia',
    'U5': 'Slovakia',
    'U6': 'Slovakia',
    'U7': 'Slovakia',
    'U8': 'Bosnia and Herzegovina',
    'U9': 'Bosnia and Herzegovina',
    'U0': 'Bosnia and Herzegovina',
    'VA': 'Austria',
    'VB': 'Austria',
    'VC': 'Austria',
    'VD': 'Austria',
    'VE': 'Austria',
    'VF': 'France',
    'VG': 'France',
    'VH': 'France',
    'VI': 'France',
    'VJ': 'France',
    'VK': 'France',
    'VL': 'France',
    'VM': 'France',
    'VN': 'France',
    'VO': 'France',
    'VP': 'France',
    'VQ': 'France',
    'VR': 'France',
    'VS': 'Spain',
    'VT': 'Spain',
    'VU': 'Spain',
    'VV': 'Spain',
    'VW': 'Spain',
    'VX': 'Serbia',
    'VY': 'Serbia',
    'VZ': 'Serbia',
    'V1': 'Serbia',
    'V2': 'Serbia',
    'V3': 'Croatia',
    'V4': 'Croatia',
    'V5': 'Croatia',
    'V6': 'Estonia',
    'V7': 'Estonia',
    'V8': 'Estonia',
    'V9': 'Estonia',
    'V0': 'Estonia',
    'W': 'Germany',
    'X': 'Russia',
    'Y': 'Sweden',
    'Z': 'Italy',
    '1': 'USA',
    '4': 'USA',
    '5': 'USA',
    '7': 'USA',
    'F': 'USA',
    'T': 'USA',
    '70': 'USA',
    '2': 'Canada',
    '3A': 'Mexico',
    '3B': 'Mexico',
    '3C': 'Mexico',
    '3D': 'Mexico',
    '3E': 'Mexico',
    '3F': 'Mexico',
    '3G': 'Mexico',
    '3H': 'Mexico',
    '3I': 'Mexico',
    '3J': 'Mexico',
    '3K': 'Mexico',
    '3L': 'Mexico',
    '3M': 'Mexico',
    '3N': 'Mexico',
    '3O': 'Mexico',
    '3P': 'Mexico',
    '3Q': 'Mexico',
    '3R': 'Mexico',
    '3S': 'Mexico',
    '3T': 'Mexico',
    '3U': 'Mexico',
    '3V': 'Mexico',
    '3W': 'Mexico',
    '3X': 'Mexico',
    '3Y': 'Costa Rica',
    '3Z': 'Costa Rica',
    '37': 'Costa Rica',
    '38': 'Cayman Islands',
    '39': 'Cayman Islands',
    '6': 'Australia',
    '7A': 'New Zealand',
    '7B': 'New Zealand',
    '7C': 'New Zealand',
    '7D': 'New Zealand',
    '7E': 'New Zealand',
    '8A': 'Argentina',
    '8B': 'Argentina',
    '8C': 'Argentina',
    '8D': 'Argentina',
    '8E': 'Argentina',
    '8F': 'Chile',
    '8G': 'Chile',
    '8H': 'Chile',
    '8I': 'Chile',
    '8J': 'Chile',
    '8K': 'Chile',
    '8L': 'Ecuador',
    '8M': 'Ecuador',
    '8N': 'Ecuador',
    '8O': 'Ecuador',
    '8P': 'Ecuador',
    '8Q': 'Ecuador',
    '8R': 'Ecuador',
    '8S': 'Peru',
    '8T': 'Peru',
    '8U': 'Peru',
    '8V': 'Peru',
    '8W': 'Peru',
    '8X': 'Venezuela',
    '8Y': 'Venezuela',
    '8Z': 'Venezuela',
    '82': 'Venezuela',
    '9A': 'Brazil',
    '9B': 'Brazil',
    '9C': 'Brazil',
    '9D': 'Brazil',
    '9E': 'Brazil',
    '9F': 'Colombia',
    '9G': 'Colombia',
    '9H': 'Colombia',
    '9I': 'Colombia',
    '9J': 'Colombia',
    '9K': 'Colombia',
    '9L': 'Paraguay',
    '9M': 'Paraguay',
    '9N': 'Paraguay',
    '9O': 'Paraguay',
    '9P': 'Paraguay',
    '9Q': 'Paraguay',
    '9R': 'Paraguay',
    '9S': 'Uruguay',
    '9T': 'Uruguay',
    '9U': 'Uruguay',
    '9V': 'Uruguay',
    '9W': 'Uruguay',
    '9X': 'Trinidad & Tobago',
    '9Y': 'Trinidad & Tobago',
    '9Z': 'Trinidad & Tobago',
    '92': 'Trinidad & Tobago',
    '93': 'Brazil',
    '94': 'Brazil',
    '95': 'Brazil',
    '96': 'Brazil',
    '97': 'Brazil',
    '98': 'Brazil',
    '99': 'Brazil',
  };

  static const Map<String, String> yearCodes = {
    'A': '1980',
    'B': '1981',
    'C': '1982',
    'D': '1983',
    'E': '1984',
    'F': '1985',
    'G': '1986',
    'H': '1987',
    'J': '1988',
    'K': '1989',
    'L': '1990',
    'M': '1991',
    'N': '1992',
    'P': '1993',
    'R': '1994',
    'S': '1995',
    'T': '1996',
    'V': '1997',
    'W': '1998',
    'X': '1999',
    'Y': '2000',
    '1': '2001',
    '2': '2002',
    '3': '2003',
    '4': '2004',
    '5': '2005',
    '6': '2006',
    '7': '2007',
    '8': '2008',
    '9': '2009',
    'A0': '2010',
    'B0': '2011',
    'C0': '2012',
    'D0': '2013',
    'E0': '2014',
    'F0': '2015',
    'G0': '2016',
    'H0': '2017',
    'J0': '2018',
    'K0': '2019',
    'L0': '2020',
    'M0': '2021',
    'N0': '2022',
    'P0': '2023',
    'R0': '2024',
    'S0': '2025',
    'T0': '2026',
    'V0': '2027',
    'W0': '2028',
    'X0': '2029',
    'Y0': '2030',
    '10': '2031',
    '20': '2032',
    '30': '2033',
    '40': '2034',
    '50': '2035',
    '60': '2036',
    '70': '2037',
    '80': '2038',
    '90': '2039'
  };

  static const Map<String, String> manufacturers = {
    'AAA': 'Audi South Africa made by Volkswagen of South Africa',
    'AAK': 'FAW Vehicle Manufacturers SA (PTY) Ltd.',
    'AAM': 'MAN Automotive (South Africa) (Pty) Ltd. (includes VW Truck & Bus)',
    'AAP': 'VIN restamped by South African Police Service (so-called SAPVIN)',
    'AAV': 'Volkswagen South Africa',
    'AAW': 'Challenger Trailers (South Africa)',
    'ABJ':
        'Mitsubishi Colt & Triton pickups made by Mercedes-Benz South Africa 1994–2011, Mitsubishi Fuso made by Daimler Trucks & Buses Southern Africa',
    'ACV': 'Isuzu Motors South Africa 2018-',
    'AC5': 'Hyundai Automotive South Africa',
    'ADD': 'UD Trucks Southern Africa (Pty) Ltd.',
    'ADM': 'General Motors South Africa (includes Isuzu through 2018)',
    'ADN': 'Nissan South Africa (Pty) Ltd.',
    'ADR': 'Renault Sandero made by Nissan South Africa (Pty) Ltd.',
    'ADX': 'Tata Automobile Corporation (SA) Ltd.',
    'AFA': 'Ford Motor Company of Southern Africa & Samcor',
    'AFB': 'Mazda BT-50 made by Ford Motor Company of Southern Africa',
    'AHH': 'Hino South Africa',
    'AHM': 'Honda Ballade made by Mercedes-Benz South Africa 1982–2000',
    'AHT': 'Toyota South Africa Motors (Pty.) Ltd.',
    'BUK': 'Kiira Motors Corporation, Uganda',
    'BR1': 'Mercedes-Benz Algeria (SAFAV MB)',
    'DF9': 'Laraki',
    'HES': 'smart Automobile Co., Ltd. (Mercedes-Geely joint venture)',
    'HL4':
        'Zhejiang Morini Vehicle Co., Ltd. (Moto Morini subsidiary of Taizhou Zhongneng Motorcycle Co., Ltd.)',
    'JAA': 'Isuzu truck',
    'JAB': 'Isuzu car',
    'JAC': 'Isuzu SUV',
    'JAE': 'Acura SLX made by Isuzu',
    'JAL':
        'Isuzu commercial trucks & Chevrolet commercial trucks made by Isuzu 2016+ & Hino S-series truck made by Isuzu (Incomplete Vehicle)',
    'JAM': 'Isuzu commercial trucks (Incomplete Vehicle)',
    'JA3': 'Mitsubishi car',
    'JA4': 'Mitsubishi MPV/SUV',
    'JA7': 'Mitsubishi truck',
    'JB3': 'Dodge car made by Mitsubishi Motors',
    'JB4': 'Dodge MPV/SUV made by Mitsubishi Motors',
    'JB7': 'Dodge truck made by Mitsubishi Motors',
    'JC0': 'Ford brand cars made by Mazda',
    'JC1': 'Fiat 124 Spider made by Mazda',
    'JC2': 'Ford Courier made by Mazda',
    'JDA': 'Daihatsu',
    'JD1': 'Daihatsu car',
    'JD2': 'Daihatsu SUV',
    'JD4': 'Daihatsu truck',
    'JE3': 'Eagle car made by Mitsubishi Motors',
    'JE4': 'Mitsubishi Motors',
    'JF1': 'Subaru car',
    'JF2': 'Subaru SUV',
    'JF3': 'Subaru truck',
    'JF4': 'Saab 9-2X made by Subaru',
    'JG1': 'Chevrolet/Geo car made by Suzuki',
    'JG7': 'Pontiac/Asuna car made by Suzuki for GM Canada',
    'JGC': 'Chevrolet/Geo SUV made by Suzuki (classified as a truck)',
    'JGT': 'GMC SUV made by Suzuki for GM Canada (classified as a truck)',
    'JHA': 'Hino truck',
    'JHB': 'Hino incomplete vehicle',
    'JHD': 'Hino',
    'JHF': 'Hino',
    'JHH': 'Hino incomplete vehicle',
    'JHF-JHG, JHL-JHN, JHZ, JH1-JH5': 'Honda',
    'JHL': 'Honda MPV/SUV',
    'JHM': 'Honda car',
    'JH1': 'Honda truck',
    'JH2': 'Honda motorcycle/ATV',
    'JH3': 'Honda ATV',
    'JH4': 'Acura car',
    'JH6': 'Hino incomplete vehicle',
    'JJ3': 'Chrysler brand car made by Mitsubishi Motors',
    'JKA': 'Kawasaki (motorcycles)',
    'JKB': 'Kawasaki (motorcycles)',
    'JKS': 'Suzuki Marauder 1600/Boulevard M95 motorcycle made by Kawasaki',
    'JK8': 'Suzuki QUV620F UTV made by Kawasaki',
    'JLF': 'Mitsubishi Fuso Truck & Bus Corp.',
    'JLS': 'Sterling Truck 360 made by Mitsubishi Fuso Truck & Bus Corp.',
    'JL5': 'Mitsubishi Fuso Truck & Bus Corp.',
    'JL6': 'Mitsubishi Fuso Truck & Bus Corp.',
    'JMA': 'Mitsubishi Motors',
    'JMB': 'Mitsubishi Motors',
    'JMF': 'Mitsubishi Motors',
    'JMY': 'Mitsubishi Motors',
    'JMZ': 'Mazda for Europe export',
    'JM0': 'Mazda for Oceania export',
    'JM1': 'Mazda car',
    'JM2': 'Mazda truck',
    'JM3': 'Mazda MPV/SUV',
    'JM6': 'Mazda',
    'JM7': 'Mazda',
    'JNA': 'Nissan Diesel/UD Trucks incomplete vehicle',
    'JNC': 'Nissan Diesel/UD Trucks',
    'JNE': 'Nissan Diesel/UD Trucks truck',
    'JNK': 'Infiniti car',
    'JNR': 'Infiniti SUV',
    'JNX': 'Infiniti incomplete vehicle',
    'JN1': 'Nissan car & Infiniti car',
    'JN3': 'Nissan incomplete vehicle',
    'JN6': 'Nissan truck',
    'JN8': 'Nissan MPV/SUV & Infiniti SUV',
    'JP3': 'Plymouth car made by Mitsubishi Motors',
    'JP4': 'Plymouth MPV/SUV made by Mitsubishi Motors',
    'JP7': 'Plymouth truck made by Mitsubishi Motors',
    'JPC': 'Nissan Diesel/UD Trucks',
    'JR2': 'Isuzu Oasis made by Honda',
    'JSA': 'Suzuki car & SUV',
    'JSK': 'Kawasaki KLX125/KLX125L motorcycle made by Suzuki',
    'JSL': '\'04-\'06 Kawasaki KFX400 ATV made by Suzuki',
    'JS1':
        'Suzuki motorcycle & Kawasaki KLX400S/KLX400SR motorcycle made by Suzuki',
    'JS2': 'Suzuki car',
    'JS3': 'Suzuki SUV',
    'JS4': 'Suzuki truck',
    'JTB': 'Toyota bus',
    'JTD': 'Toyota car',
    'JTE': 'Toyota MPV/SUV',
    'JTF': 'Toyota van/truck',
    'JTG': 'Toyota MPV/bus',
    'JTH': 'Lexus car',
    'JTJ': 'Lexus SUV',
    'JTK': 'Toyota car',
    'JTL': 'Toyota SUV',
    'JTM': 'Toyota SUV',
    'JTN': 'Toyota car',
    'JTP': 'Toyota SUV',
    'JT1': 'Toyota',
    'JT2': 'Toyota car',
    'JT3': 'Toyota MPV/SUV',
    'JT4': 'Toyota truck',
    'JT5': 'Toyota incomplete vehicle',
    'JT6': 'Lexus SUV',
    'JT8': 'Lexus car',
    'JW6': 'Mitsubishi Fuso division of Mitsubishi Motors (through mid 2003)',
    'JYA': 'Yamaha motorcycles',
    'JYE': 'Yamaha snowmobile',
    'JY3': 'Yamaha 3-wheel ATV',
    'JY4': 'Yamaha 4-wheel ATV',
    'KL': 'Daewoo General Motors South Korea',
    'KLA':
        'Daewoo/GM Daewoo/GM Korea (Chevrolet/Alpheon) from Bupyeong & Kunsan plants',
    'KLT': 'Tata Daewoo',
    'KLU': 'Tata Daewoo',
    'KLY': 'Daewoo/GM Daewoo/GM Korea (Chevrolet) from Changwon plant',
    'KL1': 'GM Daewoo/GM Korea (Chevrolet car)',
    'KL2': 'Daewoo/GM Daewoo (Pontiac)',
    'KL3': 'GM Daewoo/GM Korea (Holden)',
    'KL4': 'GM Korea (Buick)',
    'KL5': 'GM Daewoo (Suzuki)',
    'KL6': 'GM Daewoo (GMC)',
    'KL7': 'Daewoo (GM Canada brands: Passport, Asuna (Pre-2000))',
    'KL8': 'GM Daewoo/GM Korea (Chevrolet car (Spark))',
    'KM': 'Hyundai',
    'KMC': 'Hyundai commercial truck',
    'KME': 'Hyundai commercial truck (semi-tractor)',
    'KMF': 'Hyundai van & commercial truck & Bering Truck',
    'KMH': 'Hyundai car',
    'KMJ': 'Hyundai minibus/bus',
    'KMT': 'Genesis Motor car',
    'KMU': 'Genesis Motor SUV',
    'KMY': 'Daelim Motor Company, Ltd/DNA Motors Co., Ltd. (motorcycles)',
    'KM1': 'Hyosung Motors (motorcycles)',
    'KM4': 'Hyosung Motors/S&T Motors/KR Motors (motorcycles)',
    'KM8': 'Hyundai SUV',
    'KNA': 'Kia car',
    'KNC': 'Kia truck',
    'KND': 'Kia MPV/SUV & Hyundai Entourage',
    'KNE': 'Kia for Europe export',
    'KNF': 'Kia, special vehicles',
    'KNG': 'Kia minibus/bus',
    'KNJ': 'Ford Festiva & Aspire made by Kia',
    'KNM': 'Renault Samsung Motors & Nissan Rogue made by Renault Samsung',
    'KN1': 'Asia Motors',
    'KN2': 'Asia Motors',
    'KPA': 'SsangYong pickup',
    'KPB': 'SsangYong car',
    'KPH': 'Mitsubishi Precis',
    'KPT': 'SsangYong SUV/MPV',
    'LAE': 'Jinan Qingqi Motorcycle',
    'LAL': 'Sundiro Honda Motorcycle',
    'LAN': 'Changzhou Yamasaki Motorcycle',
    'LA6': 'King Long',
    'LA9': 'BYD, LC0',
    'LBB': 'Zhejiang Qianjiang Motorcycle (QJ Motor/Keeway/Benelli)',
    'LBE': 'Beijing Hyundai',
    'LBM': 'Zongshen Piaggio',
    'LBP': 'Chongqing Jianshe Yamaha Motor Co. Ltd. (motorcycles)',
    'LBV': 'BMW Brilliance',
    'LB1': 'Fujian Benz',
    'LB2': 'Geely Motorcycles',
    'LB3': 'Geely Automobile',
    'LB7': 'Tibet New Summit Motorcycle Co., Ltd.',
    'LCE': 'Hangzhou Chunfeng Motorcycles (CFMOTO)',
    'LCR': 'Gonow',
    'LC2': 'Changzhou Kwang Yang Motor Co., Ltd. (Kymco)',
    'LC6': 'Changzhou Haojue Suzuki Motorcycle Co. Ltd.',
    'LDC': 'Dongfeng Peugeot Citroen Automobile Co., Ltd. (DPCA)',
    'LDD': 'Dandong Huanghai Automobile',
    'LDF': 'Dezhou Fulu Vehicle (motorcycles)',
    'LDK': 'FAW Bus (Dalian) Co., Ltd.',
    'LDN': 'Soueast (South East (Fujian) Motor Co., Ltd.)',
    'LDP': 'Voyah, Dongfeng',
    'LDY': 'Zhongtong Bus, China',
    'LEF': 'Jiangling Motors Corporation Ltd. (JMC)',
    'LET': 'Jiangling-Isuzu Motors, China',
    'LE4': 'Beijing Benz & Beijing Benz-Daimler Chrysler Automotive Co.',
    'LFB': 'FAW Group',
    'LFG': 'Taizhou Chuanl Motorcycle Manufacturing',
    'LFN': 'FAW Bus (Wuxi) Co., Ltd.',
    'LFP': 'FAW Car, China (passenger vehicles)',
    'LFT': 'FAW, China (trailers)',
    'LFV': 'FAW-Volkswagen, China',
    'LFW': 'FAW JieFang, China',
    'LFY': 'Changshu Light Motorcycle Factory',
    'LF3': 'Lifan Motorcycle',
    'LGA': 'Dongfeng Commercial Vehicle Co., Ltd. trucks',
    'LGB': 'Dongfeng Nissan',
    'LGG': 'Dongfeng Liuzhou Motor',
    'LGJ': 'Dongfeng Fengshen (Aeolus)',
    'LGL': 'Guilin Daewoo',
    'LGW': 'Great Wall Motor',
    'LGX': 'BYD Auto',
    'LGZ': 'Guangzhou Denway Bus',
    'LHB': 'Beijing Automotive Industry Holding',
    'LHG': 'Guangzhou Honda',
    'LH1': 'FAW-Haima, China',
    'LJC': 'Jincheng Corporation',
    'LJD': 'Dongfeng Yueda Kia',
    'LJN': 'Zhengzhou Nissan',
    'LJS': 'Yaxing Coach',
    'LJU': 'Shanghai Maple Automobile & Kandi',
    'LJV': 'Sinotruk Chengdu Wangpai Commercial Vehicle Co., Ltd.',
    'LJX': 'JMC Ford',
    'LJ1': 'JAC, China',
    'LJ8': 'Zotye Auto',
    'LKC': 'Changhe',
    'LKG': 'Youngman Lotus Automobile Co., Ltd.',
    'LKL': 'Higer Bus',
    'LKT': 'Yunnan Lifan Junma Vehicle Co., Ltd. commercial vehicles',
    'LLC': 'Loncin',
    'LLN': 'Qoros',
    'LLV': 'Lifan',
    'LL3': 'Xiamen Golden Dragon Bus Co. Ltd.',
    'LL6': 'GAC Mitsubishi Motors Co., Ltd. (formerly Hunan Changfeng)',
    'LL8': 'Jiangsu Linhai Yamaha Motor Co., Ltd.',
    'LMC': 'Suzuki Hong Kong (motorcycles)',
    'LME': 'Skyworth (formerly Skywell)',
    'LMG': 'GAC Trumpchi',
    'LMV': 'XPeng Motors',
    'LMW': 'GAC Group',
    'LM6': 'SWM (automobiles)',
    'LM8': 'Seres (formerly SF Motors)',
    'LNB': 'BAIC Motor',
    'LND': 'JMEV (Jiangxi Jiangling Group New Energy Vehicle Co., Ltd.)',
    'LNP': 'NAC MG UK Limited & Nanjing Fiat Automobile',
    'LNY': 'Yuejin',
    'LPA': 'Changan PSA (DS Automobiles)',
    'LPE': 'BYD Auto',
    'LPS': 'Polestar',
    'LRB': 'SAIC General Motors Buick',
    'LRD': 'Beijing Foton Daimler Automotive Co., Ltd. Auman trucks',
    'LRE': 'SAIC General Motors Cadillac',
    'LRW': 'Tesla, Inc. (Gigafactory Shanghai)',
    'LSF': 'SAIC LDV',
    'LSG': 'SAIC General Motors Chevrolet',
    'LSH': 'SAIC Maxus van',
    'LSJ': 'SAIC MG & SAIC Roewe & IM Motors',
    'LSK': 'SAIC Maxus car',
    'LSV': 'SAIC Volkswagen, China',
    'LSY': 'Brilliance (Zhonghua) & Jinbei GM',
    'LTA': 'ZX Auto',
    'LTN': 'Soueast built Chrysler & Dodge vehicles',
    'LTP': 'National Electric Vehicle Sweden AB (NEVS)',
    'LTV': 'Toyota Tian Jin',
    'LUC': 'Honda Automobile (China)',
    'LUD': 'Dongfeng Nissan Diesel Motor Co Ltd.',
    'LUX': 'Dongfeng Yulon Motor Co. Ltd.',
    'LVA': 'Foton Motor',
    'LVB': 'Foton Motor',
    'LVC': 'Foton Motor',
    'LVF': 'Changhe Suzuki',
    'LVG': 'GAC Toyota',
    'LVH': 'Dongfeng Honda',
    'LVM': 'Chery Commercial Vehicle',
    'LVR': 'Changan Mazda',
    'LVS': 'Changan Ford & Changan Ford Mazda',
    'LVT, LVV': 'Chery Automobile',
    'LVX': 'Landwind (discontinued in 2021)',
    'LVY': 'Volvo Cars Daqing factory',
    'LVZ': 'Dongfeng Sokon Motor Company (DFSK)',
    'LV3': 'National Electric Vehicle Sweden AB (NEVS)',
    'LYV': 'Volvo Cars Chengdu factory & Luqiao factory',
    'LZE': 'Isuzu Guangzhou, China',
    'LZF': 'SAIC Iveco Hongyan',
    'LZG': 'Shaanxi Automobile Group Shacman Bus',
    'LZK': 'Sinotruk (CNHTC) Huanghe bus',
    'LZM': 'MAN China',
    'LZP': 'Zhongshan Guochi Motorcycle (Baotian)',
    'LZS': 'Zongshen',
    'LZU': 'Guangzhou Isuzu Bus',
    'LZW': 'SAIC GM Wuling',
    'LZY': 'Yutong Zhengzhou, China',
    'LZZ': 'Sinotruk (CNHTC) (Howo, Sitrak)',
    'MAB': 'Mahindra & Mahindra',
    'MAC': 'Mahindra & Mahindra',
    'MAH': 'Fiat India Automobiles Pvt. Ltd',
    'MAJ': 'Ford India',
    'MAK': 'Honda Cars India',
    'MAL': 'Hyundai Motor India',
    'MAN': 'Eicher Polaris Multix',
    'MAT': 'Tata Motors',
    'MA1': 'Mahindra & Mahindra',
    'MA3': 'Maruti Suzuki India',
    'MA6': 'GM India',
    'MA7':
        'Hindustan Motors Ltd & Mitsubishi Motors & Isuzu models made by Hindustan Motors',
    'MBF': 'Royal Enfield',
    'MBH': 'Nissan Pixo made by Maruti Suzuki India Limited',
    'MBJ': 'Toyota Kirloskar Motor Pvt. Ltd.',
    'MBK': 'MAN Trucks India Pvt. Ltd.',
    'MBL': 'Hero MotoCorp',
    'MBR': 'Mercedes-Benz India',
    'MBU': 'Swaraj Vehicles Limited',
    'MBV': 'Premier Automobiles Ltd.',
    'MBX': 'Piaggio India (Piaggio Ape)',
    'MBY': 'Asia Motor Works Ltd.',
    'MB1': 'Ashok Leyland',
    'MB8': 'Suzuki Motorcycle India Limited',
    'MCA': 'FCA India Automobiles Pvt. Ltd',
    'MCB': 'GM India',
    'MCD': 'Mahindra Two Wheelers',
    'MC2': 'Volvo Eicher commercial vehicles limited.',
    'MDH': 'Nissan Motor India Pvt Ltd.',
    'MD2': 'Bajaj Auto Ltd. & KTM and Husqvarna models built by Bajaj',
    'MD6': 'TVS Motor Company',
    'MD7': 'LML Ltd including Genuine Scooter Company Stella',
    'MD9': 'Shuttle Cars India',
    'MEC': 'Daimler India Commercial Vehicles (BharatBenz)',
    'MEE': 'Renault India Private Limited',
    'MEG': 'Harley-Davidson India',
    'MER': 'Benelli India',
    'MET': 'Piaggio India (Vespa)',
    'MEX': 'Škoda Auto Volkswagen India Pvt. Ltd. 2015 on',
    'ME1': 'India Yamaha Motor Pvt. Ltd.',
    'ME3': 'Royal Enfield',
    'ME4': 'Honda Motorcycle and Scooter India',
    'MYH': 'Ather Energy',
    'MZB': 'Kia India Pvt. Ltd.',
    'MZD': 'Classic Legends Private Limited – Jawa',
    'MZ7': 'MG Motor India Pvt. Ltd.',
    'M3G': 'Isuzu Motors India',
    'MHF': 'Toyota Indonesia (PT Toyota Motor Manufacturing Indonesia)',
    'MHK': 'PT Astra Daihatsu Motor (includes Toyotas made by Astra Daihatsu)',
    'MHL': 'PT Mercedes-Benz Indonesia',
    'MHR': 'Honda Indonesia (PT Honda Prospect Motor) (car)',
    'MHY': 'PT Suzuki Indomobil Motor',
    'MH1': 'PT Astra Honda Motor (motorcycle)',
    'MH3': 'PT Yamaha Indonesia Motor Mfg.',
    'MH4': 'PT Kawasaki Motor Indonesia',
    'MJB': 'GM Indonesia',
    'MK2': 'PT Mitsubishi Motors Krama Yudha Indonesia',
    'MK3': 'PT SGMW Motor Indonesia (Wuling)',
    'MLC': 'Thai Suzuki Motor Co., Ltd.',
    'MLE': 'Thai Yamaha Motor Co., Ltd.',
    'MLH': 'Honda Thailand (motorcycle)',
    'MLY': 'Harley-Davidson',
    'ML0': 'Ducati Motor (Thailand) Co., Ltd.',
    'ML3': 'Mitsubishi Motors (Thailand)',
    'ML5': 'Kawasaki Motors Enterprise Co. Ltd. (Thailand)',
    'MMA': 'Mitsubishi Motors (Thailand)',
    'MMB': 'Mitsubishi Motors (Thailand)',
    'MMC': 'Mitsubishi Motors (Thailand)',
    'MMD': 'Mitsubishi Motors (Thailand)',
    'MMF': 'BMW Thailand',
    'MML': 'MG Thailand (SAIC-CP)',
    'MMM': 'Chevrolet Thailand',
    'MMR': 'Subaru Thailand',
    'MMS': 'Suzuki Thailand',
    'MMT': 'Mitsubishi Motors (Thailand)',
    'MMU': 'Holden Thailand',
    'MM0, MM6, MM7, MM8':
        'Mazda Thailand (Ford-Mazda AutoAlliance Thailand plant)',
    'MNA':
        'Ford Thailand (Ford-Mazda AutoAlliance Thailand plant) for Australia/New Zealand export',
    'MNB':
        'Ford Thailand (Ford-Mazda AutoAlliance Thailand plant) for other right-hand drive markets',
    'MNC':
        'Ford Thailand (Ford-Mazda AutoAlliance Thailand plant) for left-hand drive markets',
    'MNK': 'Hino Motors Manufacturing Thailand Co Ltd',
    'MNT': 'Nissan Thailand',
    'MPA': 'Isuzu Thailand',
    'MPB': 'Ford Thailand (Ford Thailand Manufacturing plant)',
    'MP1': 'Isuzu Thailand',
    'MP2': 'Mazda BT-50 pickup built by Isuzu Motors (Thailand) Co., Ltd.',
    'MP5': 'Foton Motor Thailand',
    'MRH': 'Honda Thailand (car)',
    'MR0': 'Toyota Thailand',
    'MR1': 'Toyota Thailand',
    'MR2': 'Toyota Thailand (Gateway plant)',
    'MS0': 'SSS MOTORS Myanmar',
    'MS3': 'Suzuki Myanmar Motor Co., Ltd.',
    'MXV': 'IMZ-Ural Ural Motorcycles',
    'MX3': 'Hyundai Trans Auto',
    'NAA': 'Iran Khodro (Peugeot Iran)',
    'NAP': 'Pars Khodro',
    'NC9': 'VIRA Diesel',
    'NFB': 'Honda Atlas Cars Pakistan Ltd.',
    'NG3': 'Lucky Motor Corporation',
    'NLA': 'Honda Turkiye A.S. cars',
    'NLC': 'Askam Kamyon Imalat Ve Ticaret A.S.',
    'NLE': 'Mercedes-Benz Türk Truck',
    'NLH': 'Hyundai Assan Otomotiv car/SUV',
    'NLJ': 'Hyundai Assan Otomotiv van',
    'NLN': 'Karsan',
    'NLR': 'OTOKAR',
    'NLT': 'TEMSA',
    'NL1': 'TOGG',
    'NMA': 'MAN Türkiye A.Ş.',
    'NMB': 'Mercedes-Benz Türk A.S. Buses',
    'NMC': 'BMC Otomotiv Sanayi ve Ticaret A.Ş.',
    'NMH': 'Honda Anadolu motorcycle',
    'NMT': 'Toyota Motor Manufacturing Turkey',
    'NM0': 'Ford Otosan',
    'NM1': 'Oyak Renault Otomobil Fabrikaları A.Ş.',
    'NM4': 'Tofaş (Turk Otomobil Fabrikasi AS)',
    'NNA': 'Anadolu Isuzu',
    'NP9': 'Bozankaya',
    'PAB': 'Isuzu Philippines Corporation',
    'PAD': 'Honda Cars Philippines',
    'PE1': 'Ford Motor Company Philippines',
    'PE3': 'Mazda Philippines made by Ford Motor Company Philippines',
    'PL1': 'Proton, Malaysia',
    'PL8': 'Hyundai/Inokom',
    'PLP': 'Subaru',
    'PLZ': 'Isuzu Malaysia',
    'PMH': 'Honda car',
    'PMK': 'Honda Boon Siew motorcycle',
    'PML': 'Hicom',
    'PMN': 'Modenas',
    'PMV': 'Hong Leong Yamaha Motor Sdn. Bhd.',
    'PM1': 'BMW',
    'PM2': 'Perodua',
    'PM9': 'Bufori',
    'PNA': 'Naza/Kia/Peugeot',
    'PNV': 'Volvo Car Manufacturing Malaysia',
    'PN1': 'Toyota',
    'PN2': 'Toyota',
    'PN8': 'Nissan',
    'PPP': 'Suzuki',
    'PPV': 'Volkswagen',
    'PP1': 'Mazda',
    'PP3': 'Hyundai',
    'PRA': 'Sinotruk',
    'PRH': 'Chery',
    'PR8': 'Ford',
    'RA1': 'Steyr Trucks International FZE, UAE',
    'LFA': 'Ford Lio Ho Motor Co Ltd. old designation',
    'LFZ': 'Leapmotor',
    'LM1':
        'Tai Ling Motor Co Ltd. old designation (Suzuki motorcycle made by Tai Ling)',
    'LM4':
        'Tai Ling Motor Co Ltd. old designation (Suzuki ATV made by Tai Ling)',
    'LN1':
        'Tai Ling Motor Co Ltd. old designation (Suzuki motorcycle made by Tai Ling)',
    'LPR': 'Yamaha Motor Taiwan Co. Ltd. old designation',
    'RFB': 'Kymco, Taiwan',
    'RFC': 'Taiwan Golden Bee',
    'RFD': 'Tai Ling Motor Co Ltd. new designation',
    'RFG': 'Sanyang Motor Co., Ltd. (SYM) Taiwan',
    'RFL': 'Adly, Taiwan',
    'RFT': 'CPI Motor Company, Taiwan',
    'RFV': 'PGO Scooters including Genuine Scooter Company models made by PGO',
    'RF3': 'Aeon Motor, Taiwan',
    'RF5': 'Yulon Motor Co. Ltd., Taiwan',
    'RGS': 'Kawasaki made by Kymco',
    'RHA': 'Ford Lio Ho Motor Co Ltd. new designation',
    'RKJ': 'Prince Motors Taiwan',
    'RKL': 'Kuozui Motors (Toyota)',
    'RKM': 'China Motor Corporation',
    'RKR': 'Yamaha Motor Taiwan Co. Ltd. new designation',
    'RKT': 'Honda Taiwan',
    'RK7':
        'Kawasaki ATV made by Tai Ling Motor Co Ltd (rebadged Suzuki ATV) new designation',
    'RLA': 'Vina Star Motors Corp. – Mitsubishi',
    'RLC': 'Yamaha Motor Vietnam Co. Ltd.',
    'RLE': 'Isuzu Vietnam Co.',
    'RLH': 'Honda Vietnam Co. Ltd.',
    'RLL': 'VinFast SUV',
    'RLM': 'Mercedes-Benz Vietnam',
    'RLV': 'Vietnam Precision Industrial CO., Ltd. (Can-Am DS 70 & DS 90)',
    'RL0': 'Ford Vietnam',
    'RL4': 'Toyota Motor Vietnam',
    'RP8': 'Piaggio Vietnam Co. Ltd.',
    'R2P': 'Evoke Electric Motorcycles (Hong Kong)',
    'R4N': 'Elyx Smart Technology Holdings (Hong Kong) Ltd.',
    'SAA': 'Austin',
    'SAB': 'Optare',
    'SAD': 'Jaguar SUV (E-Pace, F-Pace, I-Pace)',
    'SAF': 'ERF trucks',
    'SAH': 'Honda made by Austin Rover Group',
    'SAJ': 'Jaguar passenger car',
    'SAL': 'Land Rover',
    'SAM': 'Morris',
    'SAR': 'Rover & MG Rover Group',
    'SAT': 'Triumph car',
    'SAX': 'Austin-Rover Group including Sterling Cars',
    'SAY': 'Norton Motorcycles',
    'SAZ': 'Freight Rover',
    'SA9': 'Morgan',
    'SA9/005': 'Panther',
    'SA9/019': 'TVR',
    'SA9/039': 'Westfield Sportscars',
    'SA9/048': 'McLaren F1',
    'SA9/050': 'Marcos Engineering',
    'SA9/130': 'MG Sport and Racing',
    'SA9/202': 'Morgan 3-Wheeler, Super 3',
    'SBB': 'Leyland Vehicles',
    'SBC': 'Iveco Ford Truck',
    'SBJ': 'Leyland Bus',
    'SBL': 'Leyland Motors & Leyland DAF',
    'SBM': 'McLaren',
    'SBS': 'Scammell',
    'SBV': 'Kenworth & Peterbilt trucks made by Leyland Trucks',
    'SB1': 'Toyota Motor Manufacturing UK',
    'SCA': 'Rolls Royce passenger car',
    'SCB': 'Bentley passenger car',
    'SCC': 'Lotus Cars',
    'SCD': 'Reliant Motors',
    'SCE': 'DeLorean Motor Cars N. Ireland (UK)',
    'SCF': 'Aston Martin Lagonda Ltd. passenger car',
    'SCG': 'Triumph Engineering Co. Ltd. (original Triumph Motorcycle company)',
    'SCK': 'Ifor Williams Trailers',
    'SCR':
        'London Electric Vehicle Company & London Taxi Company & London Taxis International',
    'SCV': 'Volvo Truck & Bus Scotland',
    'SC6': 'INEOS Automotive SUV',
    'SDB': 'Peugeot UK (formerly Talbot)',
    'SDF': 'Dodge Trucks – UK 1981–1984',
    'SDG': 'Renault Trucks Industries 1985–1992',
    'SDK': 'Caterham Cars',
    'SDL': 'TVR',
    'SDP': 'NAC MG UK & MG Motor UK Ltd.',
    'SD7': 'Aston Martin SUV',
    'SED': 'IBC Vehicles (General Motors Luton Plant)',
    'SEG': 'Dennis Eagle Ltd.',
    'SEY': 'LDV Group Ltd.',
    'SFA': 'Ford UK',
    'SFD': 'Dennis UK',
    'SFE': 'Alexander Dennis UK',
    'SFN': 'Foden Trucks',
    'SFZ': 'Tesla Roadster made by Lotus',
    'SGB': 'Bailey (caravans)',
    'SHH': 'Honda UK passenger car',
    'SHS': 'Honda UK SUV',
    'SH7': 'INEOS Automotive truck',
    'SJA': 'Bentley SUV',
    'SJK': 'Nissan Motor Manufacturing UK - Infiniti',
    'SJN': 'Nissan Motor Manufacturing UK - Nissan',
    'SJ1': 'Ree Automotive',
    'SKA': 'Vauxhall',
    'SKB': 'Kel-Berg Trailers & Trucks',
    'SKF': 'Bedford Vehicles',
    'SLA': 'Rolls Royce SUV',
    'SLP': 'JC Bamford Excavators Ltd.',
    'SMT': 'Triumph Motorcycles Ltd. (current Triumph Motorcycle company)',
    'SNE': 'Wartburg',
    'SNT': 'Trabant',
    'SUA': 'Autosan',
    'SUD': 'Wielton (truck trailers)',
    'SUF': 'Fiat Auto Poland',
    'SUJ': 'Jelcz (Poland)',
    'SUL': 'FSC (Poland)',
    'SUP': 'FSO-Daewoo (Poland)',
    'SUU': 'Solaris Bus & Coach (Poland)',
    'SU9': 'Solaris Bus & Coach (Poland)',
    'SWV': 'TA-NO (Poland)',
    'SXE': 'Neptun Trailers',
    'SZA': 'Scania Poland',
    'TCC': 'Micro Compact Car AG (smart 1998-1999) (Switzerland)',
    'TDM': 'QUANTYA Swiss Electric Movement (Switzerland)',
    'TEB': 'Bucher Municipal AG (Switzerland)',
    'TK9/SL5': 'SOR Libchavy buses (Czech Republic)',
    'TLJ': 'Jawa Moto (Czech Republic)',
    'TMA': 'Hyundai Motor Manufacturing Czech',
    'TMB': 'Škoda (Czech Republic)',
    'TMC': 'Hyundai Motor Manufacturing Czech',
    'TMK': 'Karosa (Czech Republic)',
    'TMP': 'Škoda trolleybuses (Czech Republic)',
    'TMT': 'Tatra passenger car (Czech Republic)',
    'TM9': 'Škoda trolleybuses (Czech Republic)',
    'TNA': 'Avia/Daewoo Avia',
    'TNE': 'TAZ',
    'TNT': 'Tatra trucks',
    'TNU': 'Tatra trucks',
    'TN9': 'Karosa (Czech Republic)',
    'TRA': 'Ikarus Bus',
    'TRU': 'Audi Hungary',
    'TSB': 'Ikarus Bus',
    'TSE': 'Ikarus Egyedi Autobuszgyar, (Hungary)',
    'TSM': 'Suzuki Hungary',
    'TW1': 'Toyota Caetano Portugal',
    'TW2': 'Ford Portugal',
    'TW4': 'UMM (Portugal)',
    'TYA': 'Mitsubishi Fuso Truck and Bus Corp. Portugal',
    'TYB': 'Mitsubishi Fuso Truck and Bus Corp. Portugal',
    'UH9/DA3': 'DAB - Danish Automobile Building (acquired by Scania)',
    'UN1': 'Ford Ireland',
    'UU1': 'Dacia (Romania)',
    'UU2': 'Oltcit',
    'UU3': 'ARO',
    'UU4': 'Roman SA',
    'UU5': 'Rocar',
    'UU6': 'Daewoo Romania',
    'UU7': 'Euro Bus Diamond',
    'UU9': 'Astra Bus',
    'UV9': 'ATP Bus',
    'UWR': 'Robus Reșița',
    'UZT': 'UTB (Uzina de Tractoare Brașov)',
    'U5Y': 'Kia Motors Slovakia',
    'U6Y': 'Kia Motors Slovakia',
    'VAG': 'Steyr-Daimler-Puch Puch G & Steyr-Puch Pinzgauer',
    'VAK': 'Kässbohrer Transport Technik',
    'VAN': 'MAN Austria/Steyr-Daimler-Puch Steyr Trucks',
    'VAV': 'Schwarzmüller',
    'VA0': 'ÖAF',
    'VBK': 'Husqvarna Motorcycles & Gas Gas under KTM ownership',
    'VCF': 'Fisker Inc. (Fisker Ocean) made by Magna Steyr',
    'VF1': 'Renault',
    'VF2': 'Renault Trucks',
    'VF3': 'Peugeot',
    'VF4': 'Talbot',
    'VF5': 'Iveco Unic',
    'VF6': 'Renault Trucks',
    'VF7': 'Citroën',
    'VF8': 'Matra/Talbot/Simca',
    'VF9/673': 'Venturi Automobiles',
    'VF9/795': 'Bugatti Automobiles S.A.S.',
    'VFA': 'Alpine',
    'VGA': 'Peugeot Motocycles',
    'VGY': 'Lohr (truck trailers)',
    'VG5': 'MBK (motorcycles) & Yamaha Motor',
    'VG6':
        'Renault Trucks & Mack Trucks medium duty trucks made by Renault Trucks',
    'VG7': 'Renault Trucks',
    'VG8': 'Renault Trucks',
    'VJ1': 'Heuliez Bus',
    'VJ2': 'Mia Electric',
    'VK8': 'Venturi Automobiles',
    'VLG': 'Aixam-Mega',
    'VLU': 'Scania France',
    'VL4': 'Bluecar',
    'VMK': 'Renault Sport Spider',
    'VN1': 'Renault SOVAB (France)',
    'VNE': 'Iveco Bus/Irisbus (France)',
    'VNK': 'Toyota Motor Manufacturing France',
    'VNV': 'Nissan',
    'VR1': 'DS Automobiles',
    'VR3': 'Peugeot',
    'VR7': 'Citroën',
    'VXE': 'Opel Automobile Gmbh/Vauxhall van',
    'VXF': 'Fiat van',
    'VXK': 'Opel Automobile Gmbh/Vauxhall car/SUV',
    'VSA': 'Mercedes-Benz Spain',
    'VSE': 'Suzuki Spain (Santana Motors)',
    'VSK':
        'Nissan Motor Iberica SA, Nissan passenger car/MPV/van/SUV/pickup & Ford Maverick 1993–1999',
    'VSS': 'SEAT/Cupra',
    'VSX': 'Opel Spain',
    'VS1': 'Pegaso',
    'VS5': 'Renault Spain',
    'VS6': 'Ford Spain',
    'VS7': 'Citroën Spain',
    'VS8': 'Peugeot Spain',
    'VS9': 'Carrocerias Ayats (Spain)',
    'VTD': 'Montesa Honda (Honda Montesa motorcycle models)',
    'VTH': 'Derbi (motorcycles)',
    'VTL': 'Yamaha Spain (motorcycles)',
    'VTM': 'Montesa Honda (Honda motorcycle models)',
    'VTR': 'Gas Gas',
    'VTT': 'Suzuki Spain (motorcycles)',
    'VVC': 'SOR Ibérica (truck trailers)',
    'VV1': 'Lecitrailer Group (truck trailers)',
    'VV9': 'TAURO Sport Auto Spain',
    'VWA': 'Nissan Vehiculos Industriales SA, Nissan Commercial Vehicles',
    'VWF': 'Guillén Group (truck trailers)',
    'VWV': 'Volkswagen Spain',
    'VX1': 'Zastava / Yugo Yugoslavia/Serbia',
    'V31': 'Tvornica Autobusa Zagreb (TAZ)',
    'V39/AB8': 'Rimac Automobili',
    'V6A': 'Tiki car trailers (Estonia)',
    'V61': 'Respo Trailers (Estonia)',
    'WAC': 'Audi/Porsche RS 2 Avant',
    'WAG': 'Neoplan',
    'WAP': 'Alpina',
    'WAU': 'Audi car',
    'WA1': 'Audi SUV',
    'WBA': 'BMW car',
    'WBO': 'Böckmann Fahrzeugwerke GmbH (trailers)',
    'WBS': 'BMW M car',
    'WBU': 'Bürstner (caravans)',
    'WBX': 'BMW SUV',
    'WBY': 'BMW i car',
    'WB1': 'BMW Motorrad',
    'WB3': 'BMW Motorrad Motorcycles made in India by TVS',
    'WB4': 'BMW Motorrad Motorscooters made in China by Loncin',
    'WB5': 'BMW i SUV',
    'WCD':
        'Freightliner Sprinter "bus" (van with more than 3 rows of seats) 2008–2019',
    'WDA': 'Mercedes-Benz incomplete vehicle (North America)',
    'WDB': 'Mercedes-Benz & Maybach',
    'WDC': 'Mercedes-Benz SUV',
    'WDD': 'Mercedes-Benz car',
    'WDF':
        'Mercedes-Benz van/pickup (French & Spanish built models – Citan & Vito & X-Class)',
    'WDP': 'Freightliner Sprinter incomplete vehicle 2005–2019',
    'WDR':
        'Freightliner Sprinter MPV (van with 2 or 3 rows of seats) 2005–2019',
    'WDT': 'Dethleffs (caravans)',
    'WDW':
        'Dodge Sprinter "bus" (van with more than 3 rows of seats) 2008–2009',
    'WDX': 'Dodge Sprinter incomplete vehicle 2005–2009',
    'WDY':
        'Freightliner Sprinter truck (cargo van with 1 row of seats) 2005–2019',
    'WDZ':
        'Mercedes-Benz "bus" (van with more than 3 rows of seats) (North America)',
    'WD0': 'Dodge Sprinter truck (cargo van with 1 row of seats) 2005–2009',
    'WD1':
        'Freightliner Sprinter 2002 & Sprinter (Dodge or Freightliner) 2003–2005 incomplete vehicle',
    'WD2':
        'Freightliner Sprinter 2002 & Sprinter (Dodge or Freightliner) 2003–2005 truck (cargo van with 1 row of seats)',
    'WD3':
        'Mercedes-Benz truck (cargo van with 1 row of seats) (North America)',
    'WD4': 'Mercedes-Benz MPV (van with 2 or 3 rows of seats) (North America)',
    'WD5':
        'Freightliner Sprinter 2002 & Sprinter (Dodge or Freightliner) 2003–2005 MPV (van with 2 or 3 rows of seats)',
    'WD6': 'Freightliner Unimog truck',
    'WD7': 'Freightliner Unimog incomplete vehicle',
    'WD8': 'Dodge Sprinter MPV (van with 2 or 3 rows of seats) 2005–2009',
    'WEB': 'Evobus GmbH (Mercedes-Benz buses)',
    'WEL': 'e.GO Mobile AG',
    'WFC': 'Fendt (caravans)',
    'WFD': 'Fliegl Trailer',
    'WF0': 'Ford Germany',
    'WF1': 'Merkur',
    'WHB': 'Hobby (caravans)',
    'WHD': 'Humbaur GmbH (trailers)',
    'WHW': 'Hako GmbH',
    'WJM': 'Iveco/Iveco Magirus',
    'WJR': 'Irmscher',
    'WKE': 'Krone (truck trailers)',
    'WKK': 'Setra (Evobus GmbH; formerly Kässbohrer)',
    'WKN': 'Knaus (caravans)',
    'WKV': 'Kässbohrer (truck trailers)',
    'WK0': 'Kögel (truck trailers)',
    'WLA': 'Langendorf semi-trailers',
    'WMA': 'MAN',
    'WME': 'smart (from 5/99)',
    'WMW': 'MINI car',
    'WMX':
        'Mercedes-AMG used for Mercedes-Benz SLS AMG & Mercedes-AMG GT (not used in North America)',
    'WMZ': 'MINI SUV',
    'WNA': 'Next.e.GO Mobile SE',
    'WP0': 'Porsche car',
    'WP1': 'Porsche SUV',
    'WSK': 'Schmitz-Cargobull Gotha (truck trailers)',
    'WSM': 'Schmitz-Cargobull (truck trailers)',
    'WSV': 'Aebi Schmidt Group',
    'WS5': 'StreetScooter',
    'WS7': 'Sono Motors',
    'WUA': 'Audi Sport GmbH (formerly quattro GmbH) car',
    'WU1': 'Audi Sport GmbH (formerly quattro GmbH) SUV',
    'WVG': 'Volkswagen MPV/SUV',
    'WVM': 'Arbeitsgemeinschaft VW-MAN',
    'WVP': 'Viseon Bus',
    'WVW': 'Volkswagen car',
    'WV1': 'Volkswagen Commercial Vehicles',
    'WV2': 'Volkswagen Commercial Vehicles Bus/Van',
    'WV3': 'Volkswagen Trucks',
    'XG9': 'Sfakianakis bus, Greece',
    'XLA': 'DAF Bus International',
    'XLB': 'Volvo Car B.V./NedCar B.V. (Volvo Cars)',
    'XLC': 'Ford Netherlands',
    'XLE': 'Scania Netherlands',
    'XLR': 'DAF Trucks & Leyland DAF',
    'XLV': 'DAF Bus',
    'XL4': 'Lightyear',
    'XL9/003': 'Autobusfabriek Bova BV',
    'XL9/320': 'VDL Bova',
    'XL9/363': 'Spyker',
    'XL9/530': 'Ebusco',
    'XMC': 'NedCar B.V. Mitsubishi Motors',
    'XMG': 'VDL Bus International',
    'XMR': 'Nooteboom Trailers',
    'XM4': 'RAVO Holding B.V.',
    'XNC': 'NedCar B.V. Mitsubishi Motors (Colt CZC convertible)',
    'XNL': 'VDL Bus & Coach',
    'XPN': 'Knapen Trailers',
    'XP7':
        'Tesla Europe (based in the Netherlands) (Gigafactory Berlin-Brandenburg)',
    'XTA': 'Lada / AvtoVAZ (Russia)',
    'XTB': 'Moskvitch / AZLK (Russia)',
    'XTC': 'KAMAZ (Russia)',
    'XTE': 'ZAZ (Ukraine)',
    'XTF': 'GolAZ (Russia)',
    'XTH': 'GAZ (Russia)',
    'XTK': 'IzhAvto (Russia)',
    'XTM': 'MAZ (Belarus); used until 1997',
    'XTP': 'Ural (Russia)',
    'XTT': 'UAZ / Sollers (Russia)',
    'XTU': 'Trolza (Russia)',
    'XTW': 'LAZ (Ukraine)',
    'XTY': 'LiAZ (Russia)',
    'XTZ': 'ZiL (Russia)',
    'XUF': 'General Motors Russia',
    'XUU': 'AvtoTor (Russia, Chevrolet SKD)',
    'XW7': 'Toyota Motor Manufacturing Russia',
    'XW8': 'Volkswagen Group Russia',
    'XWB': 'UZ-Daewoo/GM Uzbekistan/Ravon (Uzbekistan)',
    'XWE': 'AvtoTor (Russia, Hyundai-Kia SKD)',
    'XWF': 'AvtoTor (Russia, Chevrolet Tahoe/Opel/Cadillac/Hummer SKD)',
    'X1E': 'KAvZ (Russia)',
    'X1F': 'NefAZ (Russia)',
    'X1M': 'PAZ (Russia)',
    'X4X': 'AvtoTor (Russia, BMW SKD)',
    'X7L': 'Renault AvtoFramos (Russia)',
    'X7M': 'Hyundai & Vortex (rebadged Chery) made by TagAZ (Russia)',
    'X8J': 'IMZ-Ural Ural Motorcycles',
    'X8U': 'Scania Russia',
    'X96': 'GAZ',
    'X9F': 'Ford Motor Company ZAO',
    'X9L': 'GM-AvtoVAZ',
    'X9P': 'Volvo Vostok ZAO Volvo Trucks',
    'X9X': 'Great Wall Motors',
    'YAR':
        'Toyota Motor Europe (based in Belgium) used for Toyota ProAce & Toyota ProAce City',
    'YA9': 'Lambrecht Constructie NV (truck trailers)',
    'YBW': 'Volkswagen Belgium',
    'YB1': 'Volvo Trucks Belgium (truck)',
    'YB2': 'Volvo Trucks Belgium (bus chassis)',
    'YB3': 'Volvo Trucks Belgium (incomplete vehicle)',
    'YB6': 'Jonckheere',
    'YCM': 'Mazda Motor Europe',
    'YC1': 'Honda Belgium NV (motorcycle)',
    'YE2': 'Van Hool (buses)',
    'YH1': 'Solifer (caravans)',
    'YH2': 'BRP Finland (Lynx snowmobiles)',
    'YH4': 'Fisker Automotive (Fisker Karma) built by Valmet Automotive',
    'YK1': 'Saab-Valmet Finland',
    'YK2, YK7': 'Sisu Auto',
    'YSC': 'Cadillac BLS (made by Saab)',
    'YSM': 'Polestar cars',
    'YSR': 'Polestar SUV',
    'YS2': 'Scania commercial vehicles (Södertälje factory)',
    'YS3': 'Saab cars',
    'YS4': 'Scania buses and bus chassis until 2002 (Katrineholm factory)',
    'YTN': 'Saab NEVS',
    'YT9/007': 'Koenigsegg',
    'YT9/034': 'Carvia',
    'YU7': 'Husaberg (motorcycles)',
    'YV1': 'Volvo cars',
    'YV2': 'Volvo trucks',
    'YV3': 'Volvo buses and bus chassis',
    'YV4': 'Volvo SUV',
    'YV5': 'Volvo Trucks incomplete vehicle',
    'YYC': 'Think Nordic (Norway)',
    'Y3M': 'MAZ (Belarus)',
    'Y4F': 'Ford Belarus',
    'Y4K': 'Geely (Belarus)',
    'Y6D': 'ZAZ / AvtoZAZ (Ukraine)',
    'Y6J': 'Bogdan group (Ukraine)',
    'Y6U': 'Škoda Auto made by Eurocar',
    'Y7B': 'Bogdan group (Ukraine)',
    'Y7C': 'Great Wall Motors made by KrASZ',
    'Y7F': 'Boryspil Bus Factory (Ukraine)',
    'Y8A': 'LAZ (Ukraine)',
    'Y9H': 'LAZ (Ukraine)',
    'ZA9': 'Lamborghini through mid 2003',
    'ZAR': 'Alfa Romeo',
    'ZAM': 'Maserati',
    'ZAP': 'Piaggio/Vespa/Gilera',
    'ZCF': 'Iveco',
    'ZDM': 'Ducati Motor Holdings SpA',
    'ZDF': 'Ferrari Dino',
    'ZFA': 'Fiat',
    'ZD3': 'Beta Motor',
    'ZD4': 'Aprilia',
    'ZE1': 'Nissan Leaf (Europe)',
    'ZFC': 'Fiat V.I.',
    'ZFF': 'Ferrari',
    'ZGU': 'Moto Guzzi',
    'ZHW': 'Lamborghini',
    'ZJM': 'Malaguti',
    'ZKH': 'Husqvarna Motorcycles Srl Under BMW ownership',
    'ZL9': 'Zenvo Automotive',
    'ZLA': 'Lancia',
    'ZOM': 'Omnia',
    'ZTY': 'Zotye Auto',
    'ZW0': 'Wiesmann',
    'ZXW': 'Xpeng Motors',
    'ZYA': 'Yadea Electric Vehicle',
    'ZYV': 'Yutong Bus',
    'ZZC': 'ZAZ',
    'ZZL': 'Zhongxing (ZX Auto)',
    'ZZM': 'Zotye Auto',
    '1FA': 'Ford Motor Company',
    '1GC': 'General Motors USA',
    '1HG': 'Honda USA',
    '1J4': 'Jeep',
    '1L4': 'Lincoln',
    '1ME': 'Mercury',
    '1N4': 'Nissan USA',
    '1VW': 'Volkswagen USA',
    '1YV': 'Mazda USA',
    '1ZV': 'Ford Mustang',
    '2C3': 'Chrysler USA',
    '2FM': 'Ford Motor Company',
    '2HG': 'Honda Canada',
    '2T2': 'Lexus RX',
    '3FA': 'Ford Mexico',
    '3VW': 'Volkswagen Mexico',
    '4F2': 'Mazda USA',
    '4T1': 'Toyota Camry',
    '5FN': 'Honda Odyssey',
    '5J6': 'Honda CR-V',
    '5L': 'Lincoln',
    '5YJ': 'Tesla USA',
    '6FP': 'Ford Australia',
    '7FA': 'Honda Canada',
    '8AP': 'Fiat Argentina',
    '8GD': 'Peugeot Brazil',
    '9BW': 'Volkswagen Brazil',
    '9BM': 'Mercedes-Benz Brazil',
    '9BR': 'Toyota Brazil',
    '9BS': 'Scania Brazil',
    '9BY': 'Agrale Brazil',
    '9C2': 'Honda Motorcycles Brazil',
    '9CD': 'Suzuki Brazil',
    '9BD': 'Fiat Brazil',
    '9BG': 'Chevrolet Brazil',
    '9BF': 'Ford Brazil',
    '9BH': 'Hyundai Brazil',
    '9BT': 'Troller Brazil',
    '9UJ': 'Chery Uruguay',
    '9UK': 'Lifan Uruguay',
    '9UL': 'Geely Uruguay',
    '9US': 'Suzuki Uruguay',
    '9UU': 'Peugeot Uruguay',
    '9UW': 'Kia Uruguay',
    '9FB': 'Renault Colombia',
    '9FC': 'Chevrolet Colombia',
    '9GD': 'Hyundai Colombia',
    '9GM': 'GM Colombia',
    '9GW': 'Great Wall Colombia',
    '9BV': 'Volvo Chile',
    '9GA': 'Chevrolet Ecuador',
    '9GB': 'BYD Ecuador',
    '9GC': 'Great Wall Ecuador',
    '9HA': 'Honda Argentina',
    '9HB': 'BMW Argentina',
    '9HC': 'Chevrolet Argentina',
    '9HD': 'Dodge Argentina',
    '9HE': 'Fiat Argentina',
    '9HF': 'Ford Argentina',
    '9HG': 'Honda Peru',
    '9HH': 'Hyundai Peru',
    '9HJ': 'Jeep Peru',
    '9HK': 'Kia Peru',
    '9HL': 'Nissan Peru',
    '9HM': 'Mercedes-Benz Peru',
    '9HN': 'Nissan Chile',
    '9HP': 'Peugeot Chile',
    '9HR': 'Renault Chile',
    '9HS': 'SsangYong Chile',
    '9HT': 'Toyota Chile',
    '9HU': 'Volkswagen Chile',
    '9HV': 'Volvo Chile',
    '9HW': 'Fiat Chile',
    '9HX': 'Honda Chile',
    '9HY': 'Hyundai Chile',
    '9JA': 'Jaguar Argentina',
    '9JB': 'Jeep Argentina',
    '9JC': 'Kia Argentina',
    '9JD': 'Land Rover Argentina',
    '9JE': 'Lexus Argentina',
    '9JF': 'Maserati Argentina',
    '9JG': 'Mazda Argentina',
    '9JH': 'Mercedes-Benz Argentina',
    '9JI': 'Mini Argentina',
    '9JJ': 'Mitsubishi Argentina',
    '9JK': 'Nissan Argentina',
    '9JL': 'Peugeot Argentina',
    '9JM': 'Porsche Argentina',
    '9JN': 'Renault Argentina',
    '9JO': 'Subaru Argentina',
    '9JP': 'Suzuki Argentina',
    '9JQ': 'Toyota Argentina',
    '9JR': 'Volkswagen Argentina',
    '9JS': 'Volvo Argentina',
    '9JT': 'Tesla Argentina',
    '9JU': 'Audi Argentina',
    '9JV': 'Bentley Argentina',
    '9JW': 'Citroën Argentina',
    '9JX': 'Ferrari Argentina',
    '9JY': 'Ford Argentina',
    '9JZ': 'Genesis Argentina',
    '9KA': 'Kawasaki Argentina',
    '9KB': 'Lamborghini Argentina',
    '9KC': 'Lotus Argentina',
    '9KD': 'McLaren Argentina',
    '9KE': 'Pagani Argentina',
    '9KF': 'Rolls-Royce Argentina',
    '9KG': 'Skoda Argentina',
    '9KH': 'Smart Argentina',
    '9KI': 'Spyker Argentina',
  };

  Map<String, String> readVinAsMap(String vin) {
    Map<String, String> result = {};
    if (vin.length != 17) {
      result['Error'] =
          'Invalid VIN length. VIN must be exactly 17 characters.';
      return result;
    }

    result['Country'] = getCountry(vin);
    result['Year'] = getYear(vin);
    result['Manufacturer'] = getManufacturer(vin);
    return result;
  }

  String getCountry(String vin) {
    return countryCodes[vin.substring(0, 2)] ?? 'Unknown country';
  }

  String getYear(String vin) {
    return yearCodes[vin.substring(9, 10)] ?? 'Unknown year';
  }

  String getManufacturer(String vin) {
    return manufacturers[vin.substring(0, 3)] ?? 'Unknown manufacturer';
  }
}
